/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

extern "C" {
#include "../include/hardware/adc.h"
}

#include <CppUTestExt/MockSupport.h>

void adc_init()
{
    mock().actualCall("adc_init");
}

void adc_gpio_init(uint gpio)
{
    mock().actualCall("adc_gpio_init").withUnsignedIntParameter("gpio", gpio);
}

void adc_select_input(uint input)
{
    mock().actualCall("adc_select_input").withUnsignedIntParameter("input", input);
}

uint16_t adc_read()
{
    return static_cast<uint16_t>(mock().actualCall("adc_read").returnUnsignedIntValue());
}

