/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

extern "C" {
#include "../include/pico/bootrom.h"
}

#include <CppUTestExt/MockSupport.h>

_Bool rom_funcs_lookup(uint32_t * table, unsigned int count)
{
    return mock().actualCall("rom_funcs_lookup").withOutputParameter("table", table).withUnsignedIntParameter("count", count).returnBoolValue();
}

void * rom_hword_as_ptr(uint16_t rom_address)
{
    return mock().actualCall("rom_hword_as_ptr").withUnsignedIntParameter("rom_address", rom_address).returnPointerValue();
}

void * rom_func_lookup_inline(uint32_t code)
{
    return mock().actualCall("rom_func_lookup_inline").withUnsignedIntParameter("code", code).returnPointerValue();
}

void reset_usb_boot(uint32_t usb_activity_gpio_pin_mask, uint32_t disable_interface_mask)
{
    mock().actualCall("reset_usb_boot").withUnsignedIntParameter("usb_activity_gpio_pin_mask", usb_activity_gpio_pin_mask).withUnsignedIntParameter("disable_interface_mask", disable_interface_mask);
}

