/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

extern "C" {
#include "../include/hardware/resets.h"
}

#include <CppUTestExt/MockSupport.h>

void reset_block(uint32_t bits)
{
    mock().actualCall("reset_block").withUnsignedIntParameter("bits", bits);
}

void unreset_block(uint32_t bits)
{
    mock().actualCall("unreset_block").withUnsignedIntParameter("bits", bits);
}

void unreset_block_wait(uint32_t bits)
{
    mock().actualCall("unreset_block_wait").withUnsignedIntParameter("bits", bits);
}

