/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

extern "C" {
#include "../include/pico/stdio.h"
}

#include <CppUTestExt/MockSupport.h>

void stdio_usb_init()
{
    mock().actualCall("stdio_usb_init");
}

void stdio_uart_init()
{
    mock().actualCall("stdio_uart_init");
}

void stdio_init_all()
{
    mock().actualCall("stdio_init_all");
}

void stdio_filter_driver(stdio_driver_t * driver)
{
    mock().actualCall("stdio_filter_driver").withOutputParameterOfType("stdio_driver_t", "driver", driver);
}

void stdio_set_translate_crlf(stdio_driver_t * driver, _Bool enabled)
{
    mock().actualCall("stdio_set_translate_crlf").withOutputParameterOfType("stdio_driver_t", "driver", driver).withBoolParameter("enabled", enabled);
}

_Bool stdio_usb_connected()
{
    return mock().actualCall("stdio_usb_connected").returnBoolValue();
}

int getchar_timeout_us(uint32_t timeout_us)
{
    return mock().actualCall("getchar_timeout_us").withUnsignedIntParameter("timeout_us", timeout_us).returnIntValue();
}

