/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

extern "C" {
#include "../include/pico/stdlib.h"
}

#include <CppUTestExt/MockSupport.h>

void setup_default_uart()
{
    mock().actualCall("setup_default_uart");
}

void set_sys_clock_48mhz()
{
    mock().actualCall("set_sys_clock_48mhz");
}

void set_sys_clock_pll(uint32_t vco_freq, uint post_div1, uint post_div2)
{
    mock().actualCall("set_sys_clock_pll").withUnsignedIntParameter("vco_freq", vco_freq).withUnsignedIntParameter("post_div1", post_div1).withUnsignedIntParameter("post_div2", post_div2);
}

_Bool check_sys_clock_khz(uint32_t freq_khz, uint * vco_freq_out, uint * post_div1_out, uint * post_div2_out)
{
    return mock().actualCall("check_sys_clock_khz").withUnsignedIntParameter("freq_khz", freq_khz).withOutputParameter("vco_freq_out", vco_freq_out).withOutputParameter("post_div1_out", post_div1_out).withOutputParameter("post_div2_out", post_div2_out).returnBoolValue();
}

_Bool set_sys_clock_khz(uint32_t freq_khz, _Bool required)
{
    return mock().actualCall("set_sys_clock_khz").withUnsignedIntParameter("freq_khz", freq_khz).withBoolParameter("required", required).returnBoolValue();
}

