/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

extern "C" {
#include "../include/pico/unique_id.h"
}

#include <CppUTestExt/MockSupport.h>

void pico_get_unique_board_id(pico_unique_board_id_t * id_out)
{
    mock().actualCall("pico_get_unique_board_id").withOutputParameterOfType("pico_unique_board_id_t", "id_out", id_out);
}

void pico_get_unique_board_id_string(char * id_out, uint len)
{
    mock().actualCall("pico_get_unique_board_id_string").withOutputParameter("id_out", id_out).withUnsignedIntParameter("len", len);
}

