/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

#include <CppUMockGen.hpp>

extern "C" {
#include "../include/hardware/adc.h"
}

#include <CppUTestExt/MockSupport.h>

namespace expect {
MockExpectedCall& adc_init();
MockExpectedCall& adc_init(unsigned int __numCalls__);
}

namespace expect {
MockExpectedCall& adc_gpio_init(CppUMockGen::Parameter<uint> gpio);
MockExpectedCall& adc_gpio_init(unsigned int __numCalls__, CppUMockGen::Parameter<uint> gpio);
}

namespace expect {
MockExpectedCall& adc_select_input(CppUMockGen::Parameter<uint> input);
MockExpectedCall& adc_select_input(unsigned int __numCalls__, CppUMockGen::Parameter<uint> input);
}

namespace expect {
MockExpectedCall& adc_read(uint16_t __return__);
MockExpectedCall& adc_read(unsigned int __numCalls__, uint16_t __return__);
}

