/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

#include <CppUMockGen.hpp>

extern "C" {
#include "../include/pico/bootrom.h"
}

#include <CppUTestExt/MockSupport.h>

namespace expect {
MockExpectedCall& rom_funcs_lookup(uint32_t * table, size_t __sizeof_table, CppUMockGen::Parameter<unsigned int> count, _Bool __return__);
MockExpectedCall& rom_funcs_lookup(unsigned int __numCalls__, uint32_t * table, size_t __sizeof_table, CppUMockGen::Parameter<unsigned int> count, _Bool __return__);
}

namespace expect {
MockExpectedCall& rom_hword_as_ptr(CppUMockGen::Parameter<uint16_t> rom_address, void * __return__);
MockExpectedCall& rom_hword_as_ptr(unsigned int __numCalls__, CppUMockGen::Parameter<uint16_t> rom_address, void * __return__);
}

namespace expect {
MockExpectedCall& rom_func_lookup_inline(CppUMockGen::Parameter<uint32_t> code, void * __return__);
MockExpectedCall& rom_func_lookup_inline(unsigned int __numCalls__, CppUMockGen::Parameter<uint32_t> code, void * __return__);
}

namespace expect {
MockExpectedCall& reset_usb_boot(CppUMockGen::Parameter<uint32_t> usb_activity_gpio_pin_mask, CppUMockGen::Parameter<uint32_t> disable_interface_mask);
MockExpectedCall& reset_usb_boot(unsigned int __numCalls__, CppUMockGen::Parameter<uint32_t> usb_activity_gpio_pin_mask, CppUMockGen::Parameter<uint32_t> disable_interface_mask);
}

