/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

#include <CppUMockGen.hpp>

extern "C" {
#include "../include/pico/stdio.h"
}

#include <CppUTestExt/MockSupport.h>

namespace expect {
MockExpectedCall& stdio_usb_init();
MockExpectedCall& stdio_usb_init(unsigned int __numCalls__);
}

namespace expect {
MockExpectedCall& stdio_uart_init();
MockExpectedCall& stdio_uart_init(unsigned int __numCalls__);
}

namespace expect {
MockExpectedCall& stdio_init_all();
MockExpectedCall& stdio_init_all(unsigned int __numCalls__);
}

namespace expect {
MockExpectedCall& stdio_filter_driver(stdio_driver_t * driver);
MockExpectedCall& stdio_filter_driver(unsigned int __numCalls__, stdio_driver_t * driver);
}

namespace expect {
MockExpectedCall& stdio_set_translate_crlf(stdio_driver_t * driver, CppUMockGen::Parameter<_Bool> enabled);
MockExpectedCall& stdio_set_translate_crlf(unsigned int __numCalls__, stdio_driver_t * driver, CppUMockGen::Parameter<_Bool> enabled);
}

namespace expect {
MockExpectedCall& stdio_usb_connected(_Bool __return__);
MockExpectedCall& stdio_usb_connected(unsigned int __numCalls__, _Bool __return__);
}

namespace expect {
MockExpectedCall& getchar_timeout_us(CppUMockGen::Parameter<uint32_t> timeout_us, int __return__);
MockExpectedCall& getchar_timeout_us(unsigned int __numCalls__, CppUMockGen::Parameter<uint32_t> timeout_us, int __return__);
}

