/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

#include <CppUMockGen.hpp>

extern "C" {
#include "../include/pico/stdlib.h"
}

#include <CppUTestExt/MockSupport.h>

namespace expect {
MockExpectedCall& setup_default_uart();
MockExpectedCall& setup_default_uart(unsigned int __numCalls__);
}

namespace expect {
MockExpectedCall& set_sys_clock_48mhz();
MockExpectedCall& set_sys_clock_48mhz(unsigned int __numCalls__);
}

namespace expect {
MockExpectedCall& set_sys_clock_pll(CppUMockGen::Parameter<uint32_t> vco_freq, CppUMockGen::Parameter<uint> post_div1, CppUMockGen::Parameter<uint> post_div2);
MockExpectedCall& set_sys_clock_pll(unsigned int __numCalls__, CppUMockGen::Parameter<uint32_t> vco_freq, CppUMockGen::Parameter<uint> post_div1, CppUMockGen::Parameter<uint> post_div2);
}

namespace expect {
MockExpectedCall& check_sys_clock_khz(CppUMockGen::Parameter<uint32_t> freq_khz, uint * vco_freq_out, size_t __sizeof_vco_freq_out, uint * post_div1_out, size_t __sizeof_post_div1_out, uint * post_div2_out, size_t __sizeof_post_div2_out, _Bool __return__);
MockExpectedCall& check_sys_clock_khz(unsigned int __numCalls__, CppUMockGen::Parameter<uint32_t> freq_khz, uint * vco_freq_out, size_t __sizeof_vco_freq_out, uint * post_div1_out, size_t __sizeof_post_div1_out, uint * post_div2_out, size_t __sizeof_post_div2_out, _Bool __return__);
}

namespace expect {
MockExpectedCall& set_sys_clock_khz(CppUMockGen::Parameter<uint32_t> freq_khz, CppUMockGen::Parameter<_Bool> required, _Bool __return__);
MockExpectedCall& set_sys_clock_khz(unsigned int __numCalls__, CppUMockGen::Parameter<uint32_t> freq_khz, CppUMockGen::Parameter<_Bool> required, _Bool __return__);
}

