/*
 * This file has been auto-generated by CppUMockGen v0.6.
 *
 * Contents will NOT be preserved if it is regenerated!!!
 */

#include <CppUMockGen.hpp>

extern "C" {
#include "../include/pico/time.h"
}

#include <CppUTestExt/MockSupport.h>

namespace expect {
MockExpectedCall& sleep_ms(CppUMockGen::Parameter<uint32_t> ms);
MockExpectedCall& sleep_ms(unsigned int __numCalls__, CppUMockGen::Parameter<uint32_t> ms);
}

